# -*- coding: utf-8 -*-
"""Rag analysis pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14B7cNtm2dWSrEWXlzxNHezuGji51JqE7
"""

!pip install pypdf  sentence-transformers faiss-cpu openai

import os
from sentence_transformers import SentenceTransformer
import faiss
from pypdf import PdfReader
import numpy as np
from openai import OpenAI

embed_model=SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

from transformers import pipeline
generator=pipeline("text-generation",
                   model="google/flan-t5-large",
                   device=0)

"""# step_1"""

def load_pdf(pdf_path):
  reader=PdfReader(pdf_path)
  text=""
  for i,page in enumerate(reader.pages):
    text+=f"\n[page{i+1}]\n"+page.extract_text()
  return text

"""# step_2"""

def split_text(text,chunk_size=500,overloop=50):
  words=text.split()
  chunks=[]
  for i in range(0,len(words),chunk_size-overloop):

   chunk=" ".join(words[i:i+chunk_size])
   chunks.append(chunk)
  return chunks





"""# step_3"""

def create_index(chunks):
  embeddings=embed_model.encode(chunks,show_progress_bar=True)
  dimension=embeddings.shape[1]
  index=faiss.IndexFlatL2(dimension)
  index.add(np.array(embeddings))
  return index,embeddings





"""# retriver for question

#step_4
"""

def retrieve(query,chunks,index,k=3):
  query_vector=embed_model.encode([query])
  D,I=index.search(np.array(query_vector),k)
  result=[]
  for i in I[0]:
    result.append(chunks[i])
  return result



"""# step_5"""

def generate_answer(query, context):
    prompt = f"""নিচের Context ব্যবহার করে প্রশ্নের উত্তর দাও।
যদি Context এ উত্তর না থাকে তাহলে বলো "আমি জানি না"।

Context:
{context}

প্রশ্ন: {query}
উত্তর:"""

    result = generator(prompt, max_length=300)
    return result[0]['generated_text']

"""# step_6"""

if __name__== "__main__":
  pdf_path="/content/7 habits.pdf"
  print("1.pdf_loading")
  text=load_pdf(pdf_path)

  print("2.spliting")
  chunks=split_text(text)
  print(f"Total_chunks:{len(chunks)}")
  print("3.creating vactor index")
  index,embeddings=create_index(chunks)
  while True:
    query=input("\nyour question")
    if query=="exit":break
    print("searching")
    result=retrieve(query,chunks,index)
    context="\n---\n".join(result)
    print("genarating")
    answer=generate_answer(query,context)
    print(answer)
    print("\ndd",result[0][:300],"---")